### ISSUE TITLE
AttributeError: 'file' object has no attribute 'seekable'

### ISSUE THREAD

**Issue by trgino** [cenk/tus.py#3]
Traceback (most recent call last):
  File "/usr/bin/tus-upload", line 11, in <module>
    load_entry_point('tus.py==1.3.2', 'console_scripts', 'tus-upload')()
  File "/usr/lib/python2.7/site-packages/tus.py", line 83, in _cmd_upload
    file_size = _get_file_size(args.file)
  File "/usr/lib/python2.7/site-packages/tus.py", line 142, in _get_file_size
    if not f.seekable():
AttributeError: 'file' object has no attribute 'seekable'

**Comment by cenkalti** [comment]
There must be `seekable()` method on file objects: https://docs.python.org/2/library/io.html#io.IOBase.seekable

What type of object are you passing as file?

What Python version are you using?

**Comment by trgino** [comment]
Python 2.7.5
dosyalar gerçekten seekable değilmi diye  manuel open seek(1) readline kontrol ettim. burada bir hata vermiyor. dediğiniz gibi benim file objectte seekable yok, nasıl yok neden yok bilemiyorum fakat kendimce çözüm ürettim ve seekable kontrollerini kaldırdım.
teşekkürler.
