### ISSUE TITLE
how to get response and location of upload in tus server?

### ISSUE THREAD

**Issue by 6273parastu** [cenk/tus.py#5]
from tusclient.request import TusRequest
from tusclient import client
my_client = client.TusClient('https://master.tus.io/files/')
uploader = my_client.uploader(f'C:/Users/parastu/Documents/upload_vod/videos/1.MP4', chunk_size=20000000)
fs = open(f'C:/Users/parastu/Documents/upload_vod/videos/1.MP4','rb')
uploader = my_client.uploader(file_stream=fs, chunk_size=20000000)
uploader.upload()
request_tus = TusRequest(uploader)
response_tus = request_tus.response_content

when i upload video , i don't know how to get response and location of upload in tus server, in this code "request_tus " return none object, please help me.

**Comment by cenkalti** [comment]
Wrong project.
https://github.com/tus/tus-py-client
