### ISSUE TITLE
400 bad request, missing token and/or file upload

### ISSUE THREAD

**Issue by MrEmperathor** [cenk/tus.py#6]
I am trying to upload a video using the fembed api but I get this error:

```
[2020-10-06 17:11:12,184] INFO Creating file endpoint
Traceback (most recent call last):
  File "/usr/local/bin/tus-upload", line 8, in <module>
    sys.exit(_cmd_upload())
  File "/usr/local/lib/python2.7/dist-packages/tus.py", line 101, in _cmd_upload
    metadata=args.metadata)
  File "/usr/local/lib/python2.7/dist-packages/tus.py", line 208, in create
    raise TusError("Create failed", response=response)
tus.TusError: TusError('Create failed', response=(500, 'pre-create hook failed: exit status 1

400 bad request, missing token and/or file upload'))
```

the command I use is:

`tus-upload tes5.mp4 https://upload245.fvs.io/upload/ --header Upload-Metadata 'token Z2VqNHZhMjNrbWFrcEhDU3JTNEJMSXRUc2hEWlF1c3ErbncvY25HMUpueEkya28yRU92OHpmUGg1eFpzbnVHdnI3T25xVytGN0tXNFo1RkUrZz09OmtHcDBzVWY2SG1HS3YrZkJaRlJBNnc9PQ name tes5.mp4' --chunk-size 25600`

**Comment by cenkalti** [comment]
The error is returned from the upload server. It is not related with this client. I think there is an authentication layer in the server and you are passing the token information in wrong header. Try passing the token in `Authorization` header instead of `Upload-Metadata`. The correct command should be:
```
tus-upload tes5.mp4 https://upload245.fvs.io/upload/ --header Authorization 'token Z2VqNHZhMjNrbWFrcEhDU3JTNEJMSXRUc2hEWlF1c3ErbncvY25HMUpueEkya28yRU92OHpmUGg1eFpzbnVHdnI3T25xVytGN0tXNFo1RkUrZz09OmtHcDBzVWY2SG1HS3YrZkJaRlJBNnc9PQ name tes5.mp4' --chunk-size 25600
```
